# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'DigitsThemes' do
	pod 'Fabric', '~> 1.5.5'
	pod 'TwitterCore', '~> 1.12.0'
    pod 'Digits', '~> 1.12.0'
    
end