# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'DigitsThemes' do
	pod 'Fabric', '~> 1.2.8'
	pod 'TwitterCore', '~> 1.9.0'
    pod 'Digits', '~> 1.9.0'
    
end

target 'DigitsThemesTests' do

end

